services:
  # next.js: 
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.next.js
  #   container_name: 2next.js
  #   working_dir: /hakason
  #   command: sh -c "npm run dev -- -H 0.0.0.0 -p 3300"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/.next
  #   ports:
  #     - "3300:3300"
  #     - "5555:5555"
  #   depends_on:
  #     - DB

  DB:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: tt
      POSTGRES_PASSWORD: tt
      POSTGRES_DB: DB
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

networks:
  default:
    name: hakason_net

volumes:
  db:
    driver: local
